# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('time', models.TimeField(max_length=100)),
                ('usercomm', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('time', models.TimeField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100000)),
            ],
        ),
    ]
